<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    <PropertyGroup>
        <RootNamespace>$(ModNameSpace)</RootNamespace>
        <AssemblyName>$(ModName)</AssemblyName>
        <AssemblyTitle>$(ModName) - Plugin</AssemblyTitle>
        <Product>$(ModName)</Product>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="TeamBMX.LobbyCompatibility" Version="*" Private="False"/>
        <PackageReference Include="AinaVT-LethalConfig" Version="*" Private="False"/>

        <PackageReference Include="LethalCompanyModding-VertexLibrary" Version="*" Private="False"/>
        <PackageReference Include="mattymatty-MonkeyInjectionLibrary" Version="*" Private="False"/>

        <PackageReference Include="Evaisa-LethalLib" Version="*" Private="False"/>
        <PackageReference Include="IAmBatby-LethalLevelLoader" Version="*" Private="False"/>
        <PackageReference Include="TeamXiaolan-DawnLib" Version="0.8.16" Private="False"/>

        <PackageReference Include="BepInEx.Core" Version="5.4.21" Private="False"/>
        <PackageReference Include="BepInEx.AssemblyPublicizer.MSBuild" Version="0.4.1" PrivateAssets="all" />

        <PackageReference
            Include="LethalCompany.GameLibs.Steam"
            Version="73.0.0-*"
            Private="False"
            Publicize="True"
        />
    </ItemGroup>

	<Target Name="CopyForUpload" AfterTargets="Build">
        <PropertyGroup>
            <DistributionDir>$(SolutionDir)\Output\dist</DistributionDir>
        </PropertyGroup>

        <PropertyGroup>
            <PluginOutDir>$(SolutionDir)\Plugin\$(OutDir)</PluginOutDir>
            <PluginsDistributionDir>$(DistributionDir)\BepInEx\plugins</PluginsDistributionDir>
        </PropertyGroup>

        <Message Importance="High" Text="Copyng Plugin to DistributionDir" />

        <MakeDir Directories="$(PluginsDistributionDir)"/>
        <ItemGroup>
            <PluginOutputFiles Include="$(PluginOutDir)\**" Exclude="$(PluginOutDir)\**\*.deps.json" />
        </ItemGroup>
        <Copy
            SourceFiles="@(PluginOutputFiles)"
            DestinationFolder="$(PluginsDistributionDir)"
        />
    </Target>
</Project>
